- name: Hello World Sample for RHACM integration demonstration
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Hello World message from RHACM automation hook
      debug:
        msg: "Hello World! Red Hat ACM here."
    - name: Output Hello World using shell
      ansible.builtin.shell: echo "Hello World! Red Hat ACM here."
