- name: Hello World Sample for RHACM integration demonstration
  hosts: all
  tasks:
    - name: Hello World message from RHACM automation hook
      debug:
        msg: "Hello World! Red Hat ACM here."

